## Import data

In [1]:
import numpy as np

# Bivariate observations 
data = np.array([[0.7, -0.3], [0.4, 0.5], [-0.2, 0.8], [-0.4, 0.3]])
data

array([[ 0.7, -0.3],
       [ 0.4,  0.5],
       [-0.2,  0.8],
       [-0.4,  0.3]])

In [2]:
# Target values of bivariate observations
output = np.array([[0.8], [0.6], [0.3], [0.3]])
output

array([[0.8],
       [0.6],
       [0.3],
       [0.3]])

In [3]:
cPoints = np.array([[0, 0], [1, -1], [-1, 1]])
cPoints

array([[ 0,  0],
       [ 1, -1],
       [-1,  1]])

## Calculate matrices

In [4]:
xMatrix = np.empty([4,4])

for i in range(0, 4):
    xMatrix[i][0] = 1
    
for j in range(0, 3):
    for i in range(0, 4):
        xMatrix[i, j + 1] = np.exp( \
            -1 * np.divide( \
                np.square(np.linalg.norm(np.subtract(data[i], cPoints[j]))), \
                  2))
        
xMatrix

array([[1.        , 0.74826357, 0.74826357, 0.10126646],
       [1.        , 0.81464732, 0.27117254, 0.33121088],
       [1.        , 0.71177032, 0.09632764, 0.71177032],
       [1.        , 0.8824969 , 0.16121764, 0.65376979]])

In [5]:
iMatrix = np.zeros([4,4])
for i in range(0,4):
    iMatrix[i, i] = 0.1

iMatrix

array([[0.1, 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. ],
       [0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0.1]])

## Calculate Ridge

In [6]:
invMatrix = np.linalg.pinv(np.dot(np.transpose(xMatrix), xMatrix) + iMatrix)

invMatrix

array([[ 4.54826202, -3.77681832, -1.86116983, -1.86155421],
       [-3.77681832,  5.98284561, -0.88542926, -1.26432443],
       [-1.86116983, -0.88542926,  4.33275508,  2.72155678],
       [-1.86155421, -1.26432443,  2.72155678,  4.53204296]])

In [7]:
coefficients = np.dot(np.dot(invMatrix, np.transpose(xMatrix)), output)

coefficients

array([[ 0.33914267],
       [ 0.19945264],
       [ 0.40096085],
       [-0.29599936]])

In [8]:
zValues = np.dot(xMatrix, coefficients)
zValues

array([[0.75843541],
       [0.51231759],
       [0.3090472 ],
       [0.38628554]])

## Calculate RMSE

In [9]:
rmse = np.sqrt(np.mean( \
        np.square(np.subtract(output, zValues)) \
    ))

rmse

0.06508238153393432