# Data importing

In [143]:
import numpy as np

x = [[1, 0.6, 0.1],
     [0, -0.4, 0.8],
     [0, 0.2, 0.5],
     [1, 0.4, -0.1]]

In [144]:
coef1 = 0.5
coef2 = 0.5

p1 = 0.3
p2 = 0.7

mean1 = [1, 1]
cov_matrix1 = [[2, 0.5], [0.5, 2]]

mean2 = [0, 0]
cov_matrix2 = [[1.5, 1], [1, 1.5]]

# E-Step

P(x|c)

In [145]:
from scipy.stats import multivariate_normal

p_x_c1 = []
for i in range(len(x)):
    if x[i][0] == 1:
        p = 0.3
    else:
        p = 0.7
    p_x_c1.append(p * multivariate_normal.pdf(x[i][1:], mean1, cov_matrix1))

p_x_c1

[0.019972589760910178,
 0.035034221769896304,
 0.047862166487579405,
 0.01771409803311908]

In [146]:
p_c1_x_prop = np.multiply(0.5, p_x_c1)
p_c1_x_prop

array([0.00998629, 0.01751711, 0.02393108, 0.00885705])

In [147]:
p_x_c2 = []
for i in range(len(x)):
    if x[i][0] == 1:
        p = 0.7
    else:
        p = 0.3
    p_x_c2.append(p * multivariate_normal.pdf(x[i][1:], mean2, cov_matrix2))

p_x_c2

[0.08373285999441,
 0.02045717409764841,
 0.03887431044487811,
 0.08715006283612474]

In [148]:
p_c2_x_prop = np.multiply(0.5, p_x_c2)
p_c2_x_prop

array([0.04186643, 0.01022859, 0.01943716, 0.04357503])

P(c|x)

In [149]:
p_c1_x = np.divide(p_c1_x_prop, np.add(p_c1_x_prop, p_c2_x_prop))
p_c1_x

array([0.19258959, 0.63134512, 0.55181128, 0.16892423])

In [150]:
p_c2_x = np.divide(p_c2_x_prop, np.add(p_c1_x_prop, p_c2_x_prop))
p_c2_x

array([0.80741041, 0.36865488, 0.44818872, 0.83107577])

N1 and N2

In [151]:
N1 = sum(p_c1_x)
N1

1.5446702187154808

In [152]:
N2 = sum(p_c2_x)
N2

2.4553297812845187

π1 and π2

In [153]:
new_coef1 = N1/(N1+N2)
new_coef1

0.38616755467887026

In [154]:
new_coef2 = N2/(N1+N2)
new_coef2

0.6138324453211298

p1 and p2

In [155]:
new_p1 = 0
for i in range(len(x)):
    new_p1 += p_c1_x[i] * x[i][0]

new_p1 = new_p1 / N1
new_p1

0.23403948408541084

In [156]:
new_p2 = 0
for i in range(len(x)):
    new_p2 += p_c2_x[i] * x[i][0]

new_p2 = new_p2 / N2
new_p2

0.6673181710330363

mean1 and mean2

In [157]:
new_mean1 = np.array([[0], [0]])
for i in range(len(x)):
    new_mean1 = np.add(new_mean1, p_c1_x[i] * np.vstack(x[i][1:]))

new_mean1 = np.divide(new_mean1, N1)
new_mean1

array([[0.026509  ],
       [0.50712978]])

In [159]:
new_mean2 = np.array([[0], [0]])
for i in range(len(x)):
    new_mean2 = np.add(new_mean2, p_c2_x[i] * np.vstack(x[i][1:]))

new_mean2 = np.divide(new_mean2, N2)
new_mean2

array([[0.30914476],
       [0.2104205 ]])

cov_matrix1 and cov_matrix2

In [158]:
new_covmatrix1 = np.array([[0, 0], [0, 0]])
for i in range(len(x)):
    new_covmatrix1 = np.add(new_covmatrix1, 
        np.dot(
            p_c1_x[i] * np.subtract(np.vstack(x[i][1:]), new_mean1),
            np.transpose(np.subtract(np.vstack(x[i][1:]), new_mean1))
        )
    )

new_covmatrix1 = np.divide(new_covmatrix1, N1)
new_covmatrix1

array([[ 0.14136501, -0.10540546],
       [-0.10540546,  0.0960526 ]])

In [160]:
new_covmatrix2 = np.array([[0, 0], [0, 0]])
for i in range(len(x)):
    new_covmatrix2 = np.add(new_covmatrix2, 
        np.dot(
            p_c2_x[i] * np.subtract(np.vstack(x[i][1:]), new_mean2),
            np.transpose(np.subtract(np.vstack(x[i][1:]), new_mean2))
        )
    )

new_covmatrix2 = np.divide(new_covmatrix2, N2)
new_covmatrix2

array([[ 0.10829305, -0.08865175],
       [-0.08865175,  0.1041233 ]])